#ifndef SYSCALLS_X86_64_H
#define SYSCALLS_X86_64_H

// clang-format off
#define SYSCALLS_NBR 328
#define SYSCALLS_ENT_X86_64                                                    \
[0  ] = { "read", NULL },                                                      \
[1  ] = { "write", NULL },                                                     \
[2  ] = { "open", NULL },                                                      \
[3  ] = { "close", NULL },                                                     \
[4  ] = { "stat", NULL },                                                      \
[5  ] = { "fstat", NULL },                                                     \
[6  ] = { "lstat", NULL },                                                     \
[7  ] = { "poll", NULL },                                                      \
[8  ] = { "lseek", NULL },                                                     \
[9  ] = { "mmap", NULL },                                                      \
[10 ] = { "mprotect", NULL },                                                  \
[11 ] = { "munmap", NULL },                                                    \
[12 ] = { "brk", NULL },                                                       \
[13 ] = { "rt_sigaction", NULL },                                              \
[14 ] = { "rt_sigprocmask", NULL },                                            \
[15 ] = { "rt_sigreturn", NULL },                                              \
[16 ] = { "ioctl", NULL },                                                     \
[17 ] = { "pread64", NULL },                                                   \
[18 ] = { "pwrite64", NULL },                                                  \
[19 ] = { "readv", NULL },                                                     \
[20 ] = { "writev", NULL },                                                    \
[21 ] = { "access", NULL },                                                    \
[22 ] = { "pipe", NULL },                                                      \
[23 ] = { "select", NULL },                                                    \
[24 ] = { "sched_yield", NULL },                                               \
[25 ] = { "mremap", NULL },                                                    \
[26 ] = { "msync", NULL },                                                     \
[27 ] = { "mincore", NULL },                                                   \
[28 ] = { "madvise", NULL },                                                   \
[29 ] = { "shmget", NULL },                                                    \
[30 ] = { "shmat", NULL },                                                     \
[31 ] = { "shmctl", NULL },                                                    \
[32 ] = { "dup", NULL },                                                       \
[33 ] = { "dup2", NULL },                                                      \
[34 ] = { "pause", NULL },                                                     \
[35 ] = { "nanosleep", NULL },                                                 \
[36 ] = { "getitimer", NULL },                                                 \
[37 ] = { "alarm", NULL },                                                     \
[38 ] = { "setitimer", NULL },                                                 \
[39 ] = { "getpid", NULL },                                                    \
[40 ] = { "sendfile", NULL },                                                  \
[41 ] = { "socket", NULL },                                                    \
[42 ] = { "connect", NULL },                                                   \
[43 ] = { "accept", NULL },                                                    \
[44 ] = { "sendto", NULL },                                                    \
[45 ] = { "recvfrom", NULL },                                                  \
[46 ] = { "sendmsg", NULL },                                                   \
[47 ] = { "recvmsg", NULL },                                                   \
[48 ] = { "shutdown", NULL },                                                  \
[49 ] = { "bind", NULL },                                                      \
[50 ] = { "listen", NULL },                                                    \
[51 ] = { "getsockname", NULL },                                               \
[52 ] = { "getpeername", NULL },                                               \
[53 ] = { "socketpair", NULL },                                                \
[54 ] = { "setsockopt", NULL },                                                \
[55 ] = { "getsockopt", NULL },                                                \
[56 ] = { "clone", NULL },                                                     \
[57 ] = { "fork", NULL },                                                      \
[58 ] = { "vfork", NULL },                                                     \
[59 ] = { "execve", "%s(\"%s\", %p, %p" },                                     \
[60 ] = { "exit", NULL },                                                      \
[61 ] = { "wait4", NULL },                                                     \
[62 ] = { "kill", NULL },                                                      \
[63 ] = { "uname", NULL },                                                     \
[64 ] = { "semget", NULL },                                                    \
[65 ] = { "semop", NULL },                                                     \
[66 ] = { "semctl", NULL },                                                    \
[67 ] = { "shmdt", NULL },                                                     \
[68 ] = { "msgget", NULL },                                                    \
[69 ] = { "msgsnd", NULL },                                                    \
[70 ] = { "msgrcv", NULL },                                                    \
[71 ] = { "msgctl", NULL },                                                    \
[72 ] = { "fcntl", NULL },                                                     \
[73 ] = { "flock", NULL },                                                     \
[74 ] = { "fsync", NULL },                                                     \
[75 ] = { "fdatasync", NULL },                                                 \
[76 ] = { "truncate", NULL },                                                  \
[77 ] = { "ftruncate", NULL },                                                 \
[78 ] = { "getdents", NULL },                                                  \
[79 ] = { "getcwd", NULL },                                                    \
[80 ] = { "chdir", NULL },                                                     \
[81 ] = { "fchdir", NULL },                                                    \
[82 ] = { "rename", NULL },                                                    \
[83 ] = { "mkdir", NULL },                                                     \
[84 ] = { "rmdir", NULL },                                                     \
[85 ] = { "creat", NULL },                                                     \
[86 ] = { "link", NULL },                                                      \
[87 ] = { "unlink", NULL },                                                    \
[88 ] = { "symlink", NULL },                                                   \
[89 ] = { "readlink", NULL },                                                  \
[90 ] = { "chmod", NULL },                                                     \
[91 ] = { "fchmod", NULL },                                                    \
[92 ] = { "chown", NULL },                                                     \
[93 ] = { "fchown", NULL },                                                    \
[94 ] = { "lchown", NULL },                                                    \
[95 ] = { "umask", NULL },                                                     \
[96 ] = { "gettimeofday", NULL },                                              \
[97 ] = { "getrlimit", NULL },                                                 \
[98 ] = { "getrusage", NULL },                                                 \
[99 ] = { "sysinfo", NULL },                                                   \
[100] = { "times", NULL },                                                     \
[101] = { "ptrace", NULL },                                                    \
[102] = { "getuid", NULL },                                                    \
[103] = { "syslog", NULL },                                                    \
[104] = { "getgid", NULL },                                                    \
[105] = { "setuid", NULL },                                                    \
[106] = { "setgid", NULL },                                                    \
[107] = { "geteuid", NULL },                                                   \
[108] = { "getegid", NULL },                                                   \
[109] = { "setpgid", NULL },                                                   \
[110] = { "getppid", NULL },                                                   \
[111] = { "getpgrp", NULL },                                                   \
[112] = { "setsid", NULL },                                                    \
[113] = { "setreuid", NULL },                                                  \
[114] = { "setregid", NULL },                                                  \
[115] = { "getgroups", NULL },                                                 \
[116] = { "setgroups", NULL },                                                 \
[117] = { "setresuid", NULL },                                                 \
[118] = { "getresuid", NULL },                                                 \
[119] = { "setresgid", NULL },                                                 \
[120] = { "getresgid", NULL },                                                 \
[121] = { "getpgid", NULL },                                                   \
[122] = { "setfsuid", NULL },                                                  \
[123] = { "setfsgid", NULL },                                                  \
[124] = { "getsid", NULL },                                                    \
[125] = { "capget", NULL },                                                    \
[126] = { "capset", NULL },                                                    \
[127] = { "rt_sigpending", NULL },                                             \
[128] = { "rt_sigtimedwait", NULL },                                           \
[129] = { "rt_sigqueueinfo", NULL },                                           \
[130] = { "rt_sigsuspend", NULL },                                             \
[131] = { "sigaltstack", NULL },                                               \
[132] = { "utime", NULL },                                                     \
[133] = { "mknod", NULL },                                                     \
[134] = { "uselib", NULL },                                                    \
[135] = { "personality", NULL },                                               \
[136] = { "ustat", NULL },                                                     \
[137] = { "statfs", NULL },                                                    \
[138] = { "fstatfs", NULL },                                                   \
[139] = { "sysfs", NULL },                                                     \
[140] = { "getpriority", NULL },                                               \
[141] = { "setpriority", NULL },                                               \
[142] = { "sched_setparam", NULL },                                            \
[143] = { "sched_getparam", NULL },                                            \
[144] = { "sched_setscheduler", NULL },                                        \
[145] = { "sched_getscheduler", NULL },                                        \
[146] = { "sched_get_priority_max", NULL },                                    \
[147] = { "sched_get_priority_min", NULL },                                    \
[148] = { "sched_rr_get_interval", NULL },                                     \
[149] = { "mlock", NULL },                                                     \
[150] = { "munlock", NULL },                                                   \
[151] = { "mlockall", NULL },                                                  \
[152] = { "munlockall", NULL },                                                \
[153] = { "vhangup", NULL },                                                   \
[154] = { "modify_ldt", NULL },                                                \
[155] = { "pivot_root", NULL },                                                \
[156] = { "_sysctl", NULL },                                                   \
[157] = { "prctl", NULL },                                                     \
[158] = { "arch_prctl", NULL },                                                \
[159] = { "adjtimex", NULL },                                                  \
[160] = { "setrlimit", NULL },                                                 \
[161] = { "chroot", NULL },                                                    \
[162] = { "sync", NULL },                                                      \
[163] = { "acct", NULL },                                                      \
[164] = { "settimeofday", NULL },                                              \
[165] = { "mount", NULL },                                                     \
[166] = { "umount2", NULL },                                                   \
[167] = { "swapon", NULL },                                                    \
[168] = { "swapoff", NULL },                                                   \
[169] = { "reboot", NULL },                                                    \
[170] = { "sethostname", NULL },                                               \
[171] = { "setdomainname", NULL },                                             \
[172] = { "iopl", NULL },                                                      \
[173] = { "ioperm", NULL },                                                    \
[174] = { "create_module", NULL },                                             \
[175] = { "init_module", NULL },                                               \
[176] = { "delete_module", NULL },                                             \
[177] = { "get_kernel_syms", NULL },                                           \
[178] = { "query_module", NULL },                                              \
[179] = { "quotactl", NULL },                                                  \
[180] = { "nfsservctl", NULL },                                                \
[181] = { "getpmsg", NULL },                                                   \
[182] = { "putpmsg", NULL },                                                   \
[183] = { "afs_syscall", NULL },                                               \
[184] = { "tuxcall", NULL },                                                   \
[185] = { "security", NULL },                                                  \
[186] = { "gettid", NULL },                                                    \
[187] = { "readahead", NULL },                                                 \
[188] = { "setxattr", NULL },                                                  \
[189] = { "lsetxattr", NULL },                                                 \
[190] = { "fsetxattr", NULL },                                                 \
[191] = { "getxattr", NULL },                                                  \
[192] = { "lgetxattr", NULL },                                                 \
[193] = { "fgetxattr", NULL },                                                 \
[194] = { "listxattr", NULL },                                                 \
[195] = { "llistxattr", NULL },                                                \
[196] = { "flistxattr", NULL },                                                \
[197] = { "removexattr", NULL },                                               \
[198] = { "lremovexattr", NULL },                                              \
[199] = { "fremovexattr", NULL },                                              \
[200] = { "tkill", NULL },                                                     \
[201] = { "time", NULL },                                                      \
[202] = { "futex", NULL },                                                     \
[203] = { "sched_setaffinity", NULL },                                         \
[204] = { "sched_getaffinity", NULL },                                         \
[205] = { "set_thread_area", NULL },                                           \
[206] = { "io_setup", NULL },                                                  \
[207] = { "io_destroy", NULL },                                                \
[208] = { "io_getevents", NULL },                                              \
[209] = { "io_submit", NULL },                                                 \
[210] = { "io_cancel", NULL },                                                 \
[211] = { "get_thread_area", NULL },                                           \
[212] = { "lookup_dcookie", NULL },                                            \
[213] = { "epoll_create", NULL },                                              \
[214] = { "epoll_ctl_old", NULL },                                             \
[215] = { "epoll_wait_old", NULL },                                            \
[216] = { "remap_file_pages", NULL },                                          \
[217] = { "getdents64", NULL },                                                \
[218] = { "set_tid_address", NULL },                                           \
[219] = { "restart_syscall", NULL },                                           \
[220] = { "semtimedop", NULL },                                                \
[221] = { "fadvise64", NULL },                                                 \
[222] = { "timer_create", NULL },                                              \
[223] = { "timer_settime", NULL },                                             \
[224] = { "timer_gettime", NULL },                                             \
[225] = { "timer_getoverrun", NULL },                                          \
[226] = { "timer_delete", NULL },                                              \
[227] = { "clock_settime", NULL },                                             \
[228] = { "clock_gettime", NULL },                                             \
[229] = { "clock_getres", NULL },                                              \
[230] = { "clock_nanosleep", NULL },                                           \
[231] = { "exit_group", NULL },                                                \
[232] = { "epoll_wait", NULL },                                                \
[233] = { "epoll_ctl", NULL },                                                 \
[234] = { "tgkill", NULL },                                                    \
[235] = { "utimes", NULL },                                                    \
[236] = { "vserver", NULL },                                                   \
[237] = { "mbind", NULL },                                                     \
[238] = { "set_mempolicy", NULL },                                             \
[239] = { "get_mempolicy", NULL },                                             \
[240] = { "mq_open", NULL },                                                   \
[241] = { "mq_unlink", NULL },                                                 \
[242] = { "mq_timedsend", NULL },                                              \
[243] = { "mq_timedreceive", NULL },                                           \
[244] = { "mq_notify", NULL },                                                 \
[245] = { "mq_getsetattr", NULL },                                             \
[246] = { "kexec_load", NULL },                                                \
[247] = { "waitid", NULL },                                                    \
[248] = { "add_key", NULL },                                                   \
[249] = { "request_key", NULL },                                               \
[250] = { "keyctl", NULL },                                                    \
[251] = { "ioprio_set", NULL },                                                \
[252] = { "ioprio_get", NULL },                                                \
[253] = { "inotify_init", NULL },                                              \
[254] = { "inotify_add_watch", NULL },                                         \
[255] = { "inotify_rm_watch", NULL },                                          \
[256] = { "migrate_pages", NULL },                                             \
[257] = { "openat", NULL },                                                    \
[258] = { "mkdirat", NULL },                                                   \
[259] = { "mknodat", NULL },                                                   \
[260] = { "fchownat", NULL },                                                  \
[261] = { "futimesat", NULL },                                                 \
[262] = { "newfstatat", NULL },                                                \
[263] = { "unlinkat", NULL },                                                  \
[264] = { "renameat", NULL },                                                  \
[265] = { "linkat", NULL },                                                    \
[266] = { "symlinkat", NULL },                                                 \
[267] = { "readlinkat", NULL },                                                \
[268] = { "fchmodat", NULL },                                                  \
[269] = { "faccessat", NULL },                                                 \
[270] = { "pselect6", NULL },                                                  \
[271] = { "ppoll", NULL },                                                     \
[272] = { "unshare", NULL },                                                   \
[273] = { "set_robust_list", NULL },                                           \
[274] = { "get_robust_list", NULL },                                           \
[275] = { "splice", NULL },                                                    \
[276] = { "tee", NULL },                                                       \
[277] = { "sync_file_range", NULL },                                           \
[278] = { "vmsplice", NULL },                                                  \
[279] = { "move_pages", NULL },                                                \
[280] = { "utimensat", NULL },                                                 \
[281] = { "epoll_pwait", NULL },                                               \
[282] = { "signalfd", NULL },                                                  \
[283] = { "timerfd_create", NULL },                                            \
[284] = { "eventfd", NULL },                                                   \
[285] = { "fallocate", NULL },                                                 \
[286] = { "timerfd_settime", NULL },                                           \
[287] = { "timerfd_gettime", NULL },                                           \
[288] = { "accept4", NULL },                                                   \
[289] = { "signalfd4", NULL },                                                 \
[290] = { "eventfd2", NULL },                                                  \
[291] = { "epoll_create1", NULL },                                             \
[292] = { "dup3", NULL },                                                      \
[293] = { "pipe2", NULL },                                                     \
[294] = { "inotify_init1", NULL },                                             \
[295] = { "preadv", NULL },                                                    \
[296] = { "pwritev", NULL },                                                   \
[297] = { "rt_tgsigqueueinfo", NULL },                                         \
[298] = { "perf_event_open", NULL },                                           \
[299] = { "recvmmsg", NULL },                                                  \
[300] = { "fanotify_init", NULL },                                             \
[301] = { "fanotify_mark", NULL },                                             \
[302] = { "prlimit64", NULL },                                                 \
[303] = { "name_to_handle_at", NULL },                                         \
[304] = { "open_by_handle_at", NULL },                                         \
[305] = { "clock_adjtime", NULL },                                             \
[306] = { "syncfs", NULL },                                                    \
[307] = { "sendmmsg", NULL },                                                  \
[308] = { "setns", NULL },                                                     \
[309] = { "getcpu", NULL },                                                    \
[310] = { "process_vm_readv", NULL },                                          \
[311] = { "process_vm_writev", NULL },                                         \
[312] = { "kcmp", NULL },                                                      \
[313] = { "finit_module", NULL },                                              \
[314] = { "sched_setattr", NULL },                                             \
[315] = { "sched_getattr", NULL },                                             \
[316] = { "renameat2", NULL },                                                 \
[317] = { "seccomp", NULL },                                                   \
[318] = { "getrandom", NULL },                                                 \
[319] = { "memfd_create", NULL },                                              \
[320] = { "kexec_file_load", NULL },                                           \
[321] = { "bpf", NULL },                                                       \
[322] = { "execveat", NULL },                                                  \
[323] = { "userfaultfd", NULL },                                               \
[324] = { "membarrier", NULL },                                                \
[325] = { "mlock2", NULL },                                                    \
[326] = { "copy_file_range", NULL },                                           \
[327] = { "preadv2", NULL },                                                   \
[328] = { "pwritev2", NULL }                                                   \

#endif  // SYSCALLS_X86_64_H
